# Generated by Django 5.2.1 on 2025-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
            ],
        ),
    ]
